---
- name: Install LEMP on target server
  hosts: targetservers
  become: yes
  tasks:
    - name: Install NGINX, MariaDB, PHP
      ansible.builtin.dnf:
        name:
          - nginx
          - mariadb105-server
          - php
          - php-fpm
        state: present
    - name: Start and enable services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - nginx
        - mariadb
        - php-fpm
    - name: Deploy PHP info page
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/info.php
        content: |
          <?php
          phpinfo();
          ?>
